// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: classes.sql

package database

import (
	"context"
)

const getClassID = `-- name: GetClassID :one
SELECT id FROM classes WHERE class_name = $1
`

func (q *Queries) GetClassID(ctx context.Context, className string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getClassID, className)
	var id int32
	err := row.Scan(&id)
	return id, err
}
