// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: classes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getClassID = `-- name: GetClassID :one
SELECT id FROM classes WHERE class_name = $1 and school_id = $2
`

type GetClassIDParams struct {
	ClassName string
	SchoolID  uuid.UUID
}

func (q *Queries) GetClassID(ctx context.Context, arg GetClassIDParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getClassID, arg.ClassName, arg.SchoolID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const validateClassInSchool = `-- name: ValidateClassInSchool :one
SELECT COUNT(*) from classes WHERE school_id = $1 and id = $2
`

type ValidateClassInSchoolParams struct {
	SchoolID uuid.UUID
	ID       int32
}

func (q *Queries) ValidateClassInSchool(ctx context.Context, arg ValidateClassInSchoolParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateClassInSchool, arg.SchoolID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
