// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: drop_targets.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addDropTarget = `-- name: AddDropTarget :one
INSERT INTO drop_targets (drop_id, type, target_id)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, drop_id, type, target_id
`

type AddDropTargetParams struct {
	DropID   uuid.UUID
	Type     TargetType
	TargetID sql.NullInt32
}

func (q *Queries) AddDropTarget(ctx context.Context, arg AddDropTargetParams) (DropTarget, error) {
	row := q.db.QueryRowContext(ctx, addDropTarget, arg.DropID, arg.Type, arg.TargetID)
	var i DropTarget
	err := row.Scan(
		&i.ID,
		&i.DropID,
		&i.Type,
		&i.TargetID,
	)
	return i, err
}
