// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: drops.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDrop = `-- name: CreateDrop :one
INSERT INTO drops (id, user_id, title, content, created_at, updated_at, post_date, expire_date)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW(),
    $4,
    $5
)
RETURNING id, user_id, title, content, created_at, updated_at, post_date, expire_date
`

type CreateDropParams struct {
	UserID     uuid.UUID
	Title      string
	Content    string
	PostDate   time.Time
	ExpireDate time.Time
}

func (q *Queries) CreateDrop(ctx context.Context, arg CreateDropParams) (Drop, error) {
	row := q.db.QueryRowContext(ctx, createDrop,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.PostDate,
		arg.ExpireDate,
	)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostDate,
		&i.ExpireDate,
	)
	return i, err
}

const deleteDrop = `-- name: DeleteDrop :exec
DELETE FROM drops WHERE id = $1
`

func (q *Queries) DeleteDrop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDrop, id)
	return err
}

const getActiveDrops = `-- name: GetActiveDrops :many
SELECT id, user_id, title, content, created_at, updated_at, post_date, expire_date FROM drops WHERE expire_date > NOW() ORDER BY post_date DESC
`

func (q *Queries) GetActiveDrops(ctx context.Context) ([]Drop, error) {
	rows, err := q.db.QueryContext(ctx, getActiveDrops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drop
	for rows.Next() {
		var i Drop
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PostDate,
			&i.ExpireDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIdFromDropID = `-- name: GetUserIdFromDropID :one
SELECT user_id FROM drops WHERE id = $1
`

func (q *Queries) GetUserIdFromDropID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserIdFromDropID, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
