// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pupils.sql

package database

import (
	"context"
	"database/sql"
)

const createPupil = `-- name: CreatePupil :one
INSERT INTO pupils (first_name, surname, class_id)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, first_name, surname, class_id
`

type CreatePupilParams struct {
	FirstName string
	Surname   string
	ClassID   sql.NullInt32
}

func (q *Queries) CreatePupil(ctx context.Context, arg CreatePupilParams) (Pupil, error) {
	row := q.db.QueryRowContext(ctx, createPupil, arg.FirstName, arg.Surname, arg.ClassID)
	var i Pupil
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.Surname,
		&i.ClassID,
	)
	return i, err
}
