// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: school.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getSchoolName = `-- name: GetSchoolName :one
SELECT name FROM schools WHERE id = $1
`

func (q *Queries) GetSchoolName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getSchoolName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
