// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: settings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addSettings = `-- name: AddSettings :exec
INSERT INTO user_settings (user_id, color_theme, layout_pref)
VALUES (
    $1,
    $2,
    $3
)
`

type AddSettingsParams struct {
	UserID     uuid.UUID
	ColorTheme string
	LayoutPref string
}

func (q *Queries) AddSettings(ctx context.Context, arg AddSettingsParams) error {
	_, err := q.db.ExecContext(ctx, addSettings, arg.UserID, arg.ColorTheme, arg.LayoutPref)
	return err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE user_settings
SET color_theme = $2, layout_pref = $3, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSettingsParams struct {
	UserID     uuid.UUID
	ColorTheme string
	LayoutPref string
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings, arg.UserID, arg.ColorTheme, arg.LayoutPref)
	return err
}
