// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: target_subscriptions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addTargetSubscription = `-- name: AddTargetSubscription :exec
INSERT INTO target_subscriptions (user_id, type, target_id)
VALUES ($1, $2, $3)
`

type AddTargetSubscriptionParams struct {
	UserID   uuid.UUID
	Type     TargetType
	TargetID int32
}

func (q *Queries) AddTargetSubscription(ctx context.Context, arg AddTargetSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, addTargetSubscription, arg.UserID, arg.Type, arg.TargetID)
	return err
}

const deleteTargetSubscriptions = `-- name: DeleteTargetSubscriptions :exec
DELETE FROM target_subscriptions WHERE user_id = $1
`

func (q *Queries) DeleteTargetSubscriptions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTargetSubscriptions, userID)
	return err
}
