//drop 1
POST http://localhost:8080/api/login
Content-Type: application/json

{"email":"emily.carter@dropletschool.co.uk","password":"password123"}

POST http://localhost:8080/api/drops
Content-Type: application/json

{
  "user_id": "ba8129e9-fb3e-48a6-a409-5ba8ed82a52d",
  "title": "Ms Carter's Meeting with Year 1",
  "content": "Year 1 come to Ms Carter's classroom at lunchtime on Monday",
  "post_date": "2025-04-01T10:00:00Z",
  "expire_date": "2025-05-01T16:00:00Z"
}

//target drop 1
POST http://localhost:8080/api/droptargets
Content-Type: application/json

{
    "drop_id": "b796ed62-ed5d-4659-8c82-ef129f703bad",
    "target_type": "YearGroup",
    "target_id": 1
}

//drop 2
POST http://localhost:8080/api/login
Content-Type: application/json

{"email":"john.wilson@dropletschool.co.uk","password":"password123"}

POST http://localhost:8080/api/drops
Content-Type: application/json

{
  "user_id": "4d331c8d-3dcc-4cfc-8948-a499d607cf05",
  "title": "6A Science on Tuesday",
  "content": "Bring your coat to the lesson on Tuesday",
  "post_date": "2025-04-01T10:00:00Z",
  "expire_date": "2025-05-01T16:00:00Z"
}

//target drop 2
POST http://localhost:8080/api/droptargets
Content-Type: application/json

{
    "drop_id": "7c9ae569-b0e1-466e-b10c-a4e4ec2ae466",
    "target_type": "Class",
    "target_id": 23
}

//drop 3
POST http://localhost:8080/api/login
Content-Type: application/json

{"email":"brian.taylor@dropletschool.co.uk","password":"password123"}

POST http://localhost:8080/api/drops
Content-Type: application/json

{
  "user_id": "fc54969e-844e-45eb-99a4-f3ab64012467",
  "title": "Running Club",
  "content": "Any Upper School pupil is invited to practise with Mr Taylor on Friday at 8am",
  "post_date": "2025-04-01T10:00:00Z",
  "expire_date": "2025-05-01T16:00:00Z"
}

//target drop 3
POST http://localhost:8080/api/droptargets
Content-Type: application/json

{
    "drop_id": "92e617b1-e5a5-459a-8e90-4cb94669ca60",
    "target_type": "Division",
    "target_id": 1
}

//drop 4
POST http://localhost:8080/api/login
Content-Type: application/json

{"email":"melissa.martin@dropletschool.co.uk","password":"password123"}

POST http://localhost:8080/api/drops
Content-Type: application/json

{
  "user_id": "707f2e08-47eb-462d-846b-1fe9bb2155e4",
  "title": "Detention",
  "content": "Mrs Martin is supervising detention for the above pupils",
  "post_date": "2025-04-01T10:00:00Z",
  "expire_date": "2025-05-01T16:00:00Z"
}

//target drop 4
POST http://localhost:8080/api/droptargets
Content-Type: application/json

{
    "drop_id": "fc805ce1-dbd0-46ba-8a4a-90d60f6a5332",
    "target_type": "Class",
    "target_id": 20
}

//drop 5
POST http://localhost:8080/api/login
Content-Type: application/json

{"email":"michael.davis@dropletschool.co.uk","password":"password123"}

POST http://localhost:8080/api/drops
Content-Type: application/json

{
  "user_id": "5cac67a9-73bd-4ec0-b7c9-ccc4804d81a4",
  "title": "Charity collection",
  "content": "Second hand clothing can be brought to Mr Davis's office until the end of the week",
  "post_date": "2025-04-01T10:00:00Z",
  "expire_date": "2025-05-01T16:00:00Z"
}


//target drop 5
POST http://localhost:8080/api/droptargets
Content-Type: application/json

{
    "drop_id": "920ba518-d5f0-40e6-8679-e8632f21d4fb",
    "target_type": "Division",
    "target_id": 1
}

POST http://localhost:8080/api/droptargets
Content-Type: application/json

{
    "drop_id": "920ba518-d5f0-40e6-8679-e8632f21d4fb",
    "target_type": "Division",
    "target_id": 2
}



/*const (
	TargetTypeStudent     TargetType = "Student"
	TargetTypeClass       TargetType = "Class"
	TargetTypeYearGroup   TargetType = "YearGroup"
	TargetTypeDivision    TargetType = "Division"
	TargetTypeCustomGroup TargetType = "CustomGroup"
	TargetTypeGeneral     TargetType = "General"
)*/