POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "securepassword",
    "role": "user"
}

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "testuser2@example.com",
    "password": "securepassword",
    "role": "user"
}

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "testuser3@example.com",
    "password": "securepassword",
    "role": "user"
}

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "testuser4@example.com",
    "password": "securepassword",
    "role": "admin"
}

GET http://localhost:8080/api/users

GET http://localhost:8080/api/users/c6eb7024-1566-4dba-9d84-ecf28257af20

GET http://localhost:8080/api/users/36c2d421-9cf2-4409-b90c-ac0883609e11

// changing role test
PUT http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "",
    "role": "admin"
}

// changing password test
PUT http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "testuser2@example.com",
    "password": "password",
    "role": ""
}

// testing login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "testuser2@example.com",
    "password": "password"
}

// testing login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "testuser3@example.com",
    "password": "securepassword"
}

//test create drop
POST http://localhost:8080/api/drops
Content-Type: application/json

{
  "user_id": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  "title": "Important Announcement",
  "content": "Meeting rescheduled to 3 PM.",
  "post_date": "2025-04-01T10:00:00Z",
  "expire_date": "2025-04-01T16:00:00Z"
}

//test delete
DELETE http://localhost:8080/api/drops/9bc1b9a8-6358-4132-b3ff-dad152d67dab

//test login, make drop, view drops
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "tester1@example.com",
    "password": "password"
}

POST http://localhost:8080/api/drops
Content-Type: application/json

{
  "user_id": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  "title": "Important Announcement",
  "content": "Meeting rescheduled to 3 PM.",
  "post_date": "2025-04-01T10:00:00Z",
  "expire_date": "2025-05-01T16:00:00Z"
}

POST http://localhost:8080/api/drops
Content-Type: application/json

{
  "user_id": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  "title": "Important Announcement Expired",
  "content": "Meeting rescheduled to 3 PM.",
  "post_date": "2025-02-01T10:00:00Z",
  "expire_date": "2025-03-01T16:00:00Z"
}

POST http://localhost:8080/api/drops
Content-Type: application/json

{
  "user_id": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  "title": "Important Announcement 2",
  "content": "Meeting rescheduled to 3 PM.",
  "post_date": "2025-04-01T10:00:00Z",
  "expire_date": "2025-05-01T16:00:00Z"
}

GET http://localhost:8080/api/drops

DELETE http://localhost:8080/api/users