name: Go CI Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true
      
      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Add ~/go/bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH
      
      - name: Run tests
        run: go test -race -v ./...